name: Feature Request
description: Suggest an idea for the Replace Commands plugin.
title: '[Feature]: '
labels: ['enhancement']
assignees:
    - ELowry
body:
    - type: markdown
      attributes:
          value: |
              > [!IMPORTANT]  
              > This template is for requesting new features or modifications to the Replace Commands plugin.
              > 
              > Please use the [Bug Report](https://github.com/ELowry/obsidian-replace-commands/issues/new?template=bug-report.yml) template for reporting bugs or unexpected behavior.
    - type: textarea
      id: summary
      attributes:
          label: Brief Summary
          description: Please try to explain the general idea you wish for us to implement in a few short sentences.
      validations:
          required: true
    - type: textarea
      id: description
      attributes:
          label: Feature Description
          description: Please try to break down your idea in as much detail as possible. Are there specific regex capabilities or UI changes you are looking for?
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives
          description: If you have thought of alternative ways to achieve your suggestion's goals, please describe them here.
      validations:
          required: false
